# Generated by Django 5.0.2 on 2024-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portpolia_site',
            new_name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portpolia_image',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
